---
# Handlers for relay role

- name: restart xray
  ansible.builtin.systemd:
    name: xray
    state: restarted
    daemon_reload: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: reload ufw
  ansible.builtin.shell: >-
    iptables -t nat -F PREROUTING &&
    iptables -t nat -F POSTROUTING &&
    ufw reload
  when: manage_ufw == "keep"

- name: save netfilter rules
  ansible.builtin.command:
    cmd: netfilter-persistent save
  when: manage_ufw == "disable"
