---
- name: Install nginx and certbot
  ansible.builtin.apt:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: true

- name: Enable nginx service
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started
